# syntax=docker/dockerfile:1
FROM node:22-alpine AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json* ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SITE_URL=https://crashx.vip
ARG NEXT_PUBLIC_SITE_NAME=CrashX
ARG NEXT_PUBLIC_SITE_TAGLINE="Crypto Crash — provably fair, instant payouts"
ARG NEXT_PUBLIC_SITE_DESCRIPTION="CrashX — provably fair Crash, fast crypto withdrawals. 18+ play responsibly."
ARG NEXT_PUBLIC_SUPPORT_EMAIL=support@crashx.vip
ARG NEXT_PUBLIC_API_URL=http://api
ARG NEXT_PUBLIC_TENANT_SLUG=crashx
ARG NEXT_PUBLIC_PUSHER_APP_KEY=
ARG NEXT_PUBLIC_REALTIME_ENABLED=true
ARG NEXT_PUBLIC_PUSHER_APP_CLUSTER=mt1
ARG NEXT_PUBLIC_WS_HOST=crashx.vip
ARG NEXT_PUBLIC_WS_PORT=443
ARG NEXT_PUBLIC_WSS_PORT=443
ARG NEXT_PUBLIC_PUSHER_SCHEME=https
ARG NEXT_PUBLIC_CRASH_REAL_MONEY=true

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_NAME=$NEXT_PUBLIC_SITE_NAME
ENV NEXT_PUBLIC_SITE_TAGLINE=$NEXT_PUBLIC_SITE_TAGLINE
ENV NEXT_PUBLIC_SITE_DESCRIPTION=$NEXT_PUBLIC_SITE_DESCRIPTION
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_TENANT_SLUG=$NEXT_PUBLIC_TENANT_SLUG
ENV NEXT_PUBLIC_PUSHER_APP_KEY=$NEXT_PUBLIC_PUSHER_APP_KEY
ENV NEXT_PUBLIC_REALTIME_ENABLED=$NEXT_PUBLIC_REALTIME_ENABLED
ENV NEXT_PUBLIC_PUSHER_APP_CLUSTER=$NEXT_PUBLIC_PUSHER_APP_CLUSTER
ENV NEXT_PUBLIC_WS_HOST=$NEXT_PUBLIC_WS_HOST
ENV NEXT_PUBLIC_WS_PORT=$NEXT_PUBLIC_WS_PORT
ENV NEXT_PUBLIC_WSS_PORT=$NEXT_PUBLIC_WSS_PORT
ENV NEXT_PUBLIC_PUSHER_SCHEME=$NEXT_PUBLIC_PUSHER_SCHEME
ENV NEXT_PUBLIC_CRASH_REAL_MONEY=$NEXT_PUBLIC_CRASH_REAL_MONEY

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
