import {
  Bell,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Copy,
  CreditCard,
  Dices,
  Flame,
  Gem,
  Gift,
  Globe,
  Headset,
  Home,
  Landmark,
  LogIn,
  Languages,
  type LucideIcon,
  Menu,
  Minus,
  Newspaper,
  Plus,
  Rocket,
  Search,
  Settings,
  UserPlus,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Trophy,
  User,
  Wallet,
  X,
} from "lucide-react";
import type { IconName } from "@/lib/types";

const map: Record<IconName, LucideIcon> = {
  home: Home,
  user: User,
  gift: Gift,
  crown: Trophy,
  support: Headset,
  deposit: Wallet,
  withdraw: Landmark,
  info: Globe,
  promo: Sparkles,
  sponsorship: Star,
  license: Shield,
  feedback: Star,
  news: Newspaper,
  vip: Trophy,
  settings: Settings,
  transactions: CreditCard,
  verified: ShieldCheck,
  spark: Sparkles,
  flame: Flame,
  bell: Bell,
  language: Languages,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  logIn: LogIn,
  signUp: UserPlus,
  copy: Copy,
  check: Check,
  plus: Plus,
  minus: Minus,
  wallet: Wallet,
  play: Gem,
  rocket: Rocket,
  dice: Dices,
  search: Search,
  shield: Shield,
};

type IconProps = React.ComponentProps<LucideIcon> & { name: IconName };

export function Icon({ name, ...props }: IconProps) {
  const Component = map[name];
  return <Component {...props} />;
}
